/******************************************************************************
 *
 * Name:	TMR.h
 * Project:	Hermon-2
 * Purpose:	Testing
 *
 ******************************************************************************/

/******************************************************************************
 *
 *  (C)Copyright 2005 - 2008 Marvell. All Rights Reserved.
 *  
 *  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF MARVELL.
 *  The copyright notice above does not evidence any actual or intended 
 *  publication of such source code.
 *  This Module contains Proprietary Information of Marvell and should be
 *  treated as Confidential.
 *  The information in this file is provided for the exclusive use of the 
 *  licensees of Marvell.
 *  Such users have the right to use, modify, and incorporate this code into 
 *  products for purposes authorized by the license agreement provided they 
 *  include this notice and the associated copyright notice with any such
 *  product. 
 *  The information in this file is provided "AS IS" without warranty.
 *
 ******************************************************************************/

/******************************************************************************
 *
 * This file was automatically generated by reg.pl using  *	TMR.csv
 *
 ******************************************************************************/

/******************************************************************************
 *
 * History:
 *
 ********* PLEASE INSERT THE CVS HISTORY OF THE PREVIOUS VERSION HERE. *********
 *******************************************************************************/

#ifndef	__INC_TMR_H
#define	__INC_TMR_H


/*
 *
 *	THE BASE ADDRESSES
 *
 */
#define	TMR1_BASE	0xD4014000
#define	TMR2_BASE	0xD4016000

/*
 *
 *	THE REGISTER DEFINES
 *
 */
#define	TMR2_CCR		(TMR2_BASE+0x0000)	/* 32 bit	Timer Clock Control Register */
#define	TMR1_CCR		(TMR1_BASE+0x0000)	/* 32 bit	Timer Clock Control Register */
#define	TMR2_TN_MM	(TMR2_BASE+0x0004)	/* Timer Match Registers Start */
#define	TMR1_TN_MM	(TMR1_BASE+0x0004)	/* Timer Match Registers Start */
#define	TMR2_CRN		(TMR2_BASE+0x0028)	/* Timer Count Registers Start */
#define	TMR1_CRN		(TMR1_BASE+0x0028)	/* Timer Count Registers Start */
#define	TMR2_SRN		(TMR2_BASE+0x0034)	/* Timer Status Registers Start */
#define	TMR1_SRN		(TMR1_BASE+0x0034)	/* Timer Status Registers Start */
#define	TMR2_IERN	(TMR2_BASE+0x0040)	/* Timer Interrupt Enable Registers Start */
#define	TMR1_IERN	(TMR1_BASE+0x0040)	/* Timer Interrupt Enable Registers Start */
#define	TMR2_PLVRN	(TMR2_BASE+0x004C)	/* Timer Preload Value Registers Start */
#define	TMR1_PLVRN	(TMR1_BASE+0x004C)	/* Timer Preload Value Registers Start */
#define	TMR2_PLCRN	(TMR2_BASE+0x0058)	/* Timer Preload Control Registers Start */
#define	TMR1_PLCRN	(TMR1_BASE+0x0058)	/* Timer Preload Control Registers Start */
#define	TMR2_WMER	(TMR2_BASE+0x0064)	/* 32 bit	Timers Watchdog Match
										 *			Enable Register
										 */
#define	TMR1_WMER	(TMR1_BASE+0x0064)	/* 32 bit	Timers Watchdog Match
										 *			Enable Register
										 */
#define	TMR2_WMR		(TMR2_BASE+0x0068)	/* 32 bit	Timers Watchdog Match
										 *			Register
										 */
#define	TMR1_WMR		(TMR1_BASE+0x0068)	/* 32 bit	Timers Watchdog Match
										 *			Register
										 */
#define	TMR2_WVR		(TMR2_BASE+0x006C)	/* 32 bit	Timers Watchdog Value
										 *			Register
										 */
#define	TMR1_WVR		(TMR1_BASE+0x006C)	/* 32 bit	Timers Watchdog Value
										 *			Register
										 */
#define	TMR2_WSR		(TMR2_BASE+0x0070)	/* 32 bit	Timers Watchdog Status
										 *			Register
										 */
#define	TMR1_WSR		(TMR1_BASE+0x0070)	/* 32 bit	Timers Watchdog Status
										 *			Register
										 */
#define	TMR2_ICRN	(TMR2_BASE+0x0074)	/* Timer Interrupt Clear Registers Start */
#define	TMR1_ICRN	(TMR1_BASE+0x0074)	/* Timer Interrupt Clear Registers Start */
#define	TMR2_WICR	(TMR2_BASE+0x0080)	/* 32 bit	Timers Watchdog Interrupt
										 *			Clear Register
										 */
#define	TMR1_WICR	(TMR1_BASE+0x0080)	/* 32 bit	Timers Watchdog Interrupt
										 *			Clear Register
										 */
#define	TMR2_CER		(TMR2_BASE+0x0084)	/* 32 bit	Timers Count Enable Register */
#define	TMR1_CER		(TMR1_BASE+0x0084)	/* 32 bit	Timers Count Enable Register */
#define	TMR2_CMR		(TMR2_BASE+0x0088)	/* 32 bit	Timers Count Mode Register */
#define	TMR1_CMR		(TMR1_BASE+0x0088)	/* 32 bit	Timers Count Mode Register */
#define	TMR2_ILRN	(TMR2_BASE+0x008C)	/* Timer Interrupt Length Registers Start */
#define	TMR1_ILRN	(TMR1_BASE+0x008C)	/* Timer Interrupt Length Registers Start */
#define	TMR2_WCR		(TMR2_BASE+0x0098)	/* 32 bit	Timers Watchdog Counter
										 *			Reset Register
										 */
#define	TMR1_WCR		(TMR1_BASE+0x0098)	/* 32 bit	Timers Watchdog Counter
										 *			Reset Register
										 */
#define	TMR2_WFAR	(TMR2_BASE+0x009C)	/* 32 bit	Timers Watchdog First
										 *			Access Register
										 */
#define	TMR1_WFAR	(TMR1_BASE+0x009C)	/* 32 bit	Timers Watchdog First
										 *			Access Register
										 */
#define	TMR2_WSAR	(TMR2_BASE+0x00A0)	/* 32 bit	Timers Watchdog Second
										 *			Access Register
										 */
#define	TMR1_WSAR	(TMR1_BASE+0x00A0)	/* 32 bit	Timers Watchdog Second
										 *			Access Register
										 */
#define	TMR2_CVWRN	(TMR2_BASE+0x00A4)	/* Timer Counters Value Write for Read
										 *			Request Start
										 */
#define	TMR1_CVWRN	(TMR1_BASE+0x00A4)	/* Timer Counters Value Write for Read
										 *			Request Start
										 */

/*
 *
 *	THE BIT DEFINES
 *
 */
/*	TMR_CCR		0x0000	Timer Clock Control Register */
/*		Bit(s) TMR_CCR_RSRV_31_7 reserved */
/* Clock source for timer #2 */
#define	TMR_CCR_CS_2_MSK			SHIFT5(0x3)			
#define	TMR_CCR_CS_2_BASE			5
/* Clock source for timer #1 */
#define	TMR_CCR_CS_1_MSK			SHIFT2(0x7)			
#define	TMR_CCR_CS_1_BASE			2
/* Clock source for timer #0 */
#define	TMR_CCR_CS_0_MSK			SHIFT0(0x3)			
#define	TMR_CCR_CS_0_BASE			0

/*	TMR_Tn_Mm	0x0004	Timer Match Registers */
/* Timer n Match register m value */
#define	TMR_TN_MM_TMR_TN_MM_MSK			SHIFT0(0xffffffff)	
#define	TMR_TN_MM_TMR_TN_MM_BASE		0

/*	TMR_CRn		0x0028	Timer Count Registers */
#define	TMR_CRN_TCRN_MSK		SHIFT0(0xffffffff)	/* Timer n count register */
#define	TMR_CRN_TCRN_BASE		0

/*	TMR_SRn		0x0034	Timer Status Registers */
/*		Bit(s) TMR_SRN_RSRV_31_3 reserved */
/* Match status of TMR_Tn_M2 */
#define	TMR_SRN_M2					BIT_2				
/* Match status of TMR_Tn_M1 */
#define	TMR_SRN_M1					BIT_1				
/* Match status of TMR_Tn_M0 */
#define	TMR_SRN_M0					BIT_0				

/*	TMR_IERn	0x0040	Timer Interrupt Enable Registers */
/*		Bit(s) TMR_IERN_RSRV_31_3 reserved */
/* Interrupt enable for match comparator 2 */
#define	TMR_IERN_IE2				BIT_2				
/* Interrupt enable for match comparator 1 */
#define	TMR_IERN_IE1				BIT_1				
/* Interrupt enable for match comparator 0 */
#define	TMR_IERN_IE0				BIT_0				

/*	TMR_PLVRn	0x004C	Timer Preload Value Registers */
#define	TMR_PLVRN_TPLVRN_MSK		SHIFT0(0xffffffff)	/* TPLVRn */
#define	TMR_PLVRN_TPLVRN_BASE		0

/*	TMR_PLCRn	0x0058	Timer Preload Control Registers */
/*		Bit(s) TMR_PLCRN_RSRV_31_2 reserved */
/* Match comparator select */
#define	TMR_PLCRN_MCS_MSK				SHIFT0(0x3)			
#define	TMR_PLCRN_MCS_BASE				0

/*	TMR_WMER	0x0064	Timers Watchdog Match Enable Register */
/*		Bit(s) TMR_WMER_RSRV_31_2 reserved */
/* Watchdog reset/interrupt enable */
#define	TMR_WMER_WRIE				BIT_1				
#define	TMR_WMER_WE					BIT_0				/* WDT count enable */

/*	TMR_WMR		0x0068	Timers Watchdog Match Register */
/*		Bit(s) TMR_WMR_RSRV_31_16 reserved */
#define	TMR_WMR_WTM_MSK				SHIFT0(0xffff)	/* 16-bit watchdog timer match */
#define	TMR_WMR_WTM_BASE			0

/*	TMR_WVR		0x006C	Timers Watchdog Value Register */
/*		Bit(s) TMR_WVR_RSRV_31_16 reserved */
#define	TMR_WVR_WTV_MSK				SHIFT0(0xffff)	/* Watchdog timer value */
#define	TMR_WVR_WTV_BASE			0

/*	TMR_WSR		0x0070	Timers Watchdog Status Register */
/*		Bit(s) TMR_WSR_RSRV_31_1 reserved */
/* Watchdog timer reset indication */
#define	TMR_WSR_WTS					BIT_0				

/*	TMR_ICRn	0x0074	Timer Interrupt Clear Registers */
/*		Bit(s) TMR_ICRN_RSRV_31_3 reserved */
/* Interrupt clear for match comparator 2 */
#define	TMR_ICRN_TCLR2				BIT_2				
/* Interrupt clear for match comparator 1 */
#define	TMR_ICRN_TCLR1				BIT_1				
/* Interrupt clear for match comparator 0 */
#define	TMR_ICRN_TCLR0				BIT_0				

/*	TMR_WICR	0x0080	Timers Watchdog Interrupt Clear Register */
/*		Bit(s) TMR_WICR_RSRV_31_1 reserved */
#define	TMR_WICR_WICLR				BIT_0				/* WDT Interrupt clear */

/*	TMR_CER		0x0084	Timers Count Enable Register */
/*		Bit(s) TMR_CER_RSRV_31_3 reserved */
#define	TMR_CER_T2EN				BIT_2				/* Timer #2 count enable */
#define	TMR_CER_T1EN				BIT_1				/* Timer #1 count enable */
#define	TMR_CER_T0EN				BIT_0				/* Timer #0 count enable */

/*	TMR_CMR		0x0088	Timers Count Mode Register */
/*		Bit(s) TMR_CMR_RSRV_31_3 reserved */
#define	TMR_CMR_T2MODE				BIT_2				/* Timer #2 count mode */
#define	TMR_CMR_T1MODE				BIT_1				/* Timer #1 count mode */
#define	TMR_CMR_T0MODE				BIT_0				/* Timer #0 count mode */

/*	TMR_ILRn	0x008C	Timer Interrupt Length Registers */
/*		Bit(s) TMR_ILRN_RSRV_31_3 reserved */
/* Interrupt length for match comparator 2 */
#define	TMR_ILRN_TNIL2				BIT_2				
/* Interrupt length for match comparator 1 */
#define	TMR_ILRN_TNIL1				BIT_1				
/* Interrupt length for match comparator 0 */
#define	TMR_ILRN_TNIL0				BIT_0				

/*	TMR_WCR		0x0098	Timers Watchdog Counter Reset Register */
/*		Bit(s) TMR_WCR_RSRV_31_1 reserved */
/* Watchdog timer counter value reset */
#define	TMR_WCR_WCR					BIT_0				

/*	TMR_WFAR	0x009C	Timers Watchdog First Access Register */
/*		Bit(s) TMR_WFAR_RSRV_31_16 reserved */
#define	TMR_WFAR_KEY_MSK				SHIFT0(0xffff)	/* Watchdog access key */
#define	TMR_WFAR_KEY_BASE				0

/*	TMR_WSAR	0x00A0	Timers Watchdog Second Access Register */
/*		Bit(s) TMR_WSAR_RSRV_31_16 reserved */
#define	TMR_WSAR_KEY_MSK				SHIFT0(0xffff)	/* Watchdog access key */
#define	TMR_WSAR_KEY_BASE				0

/*	TMR_CVWRn	0x00A4	Timer Counters Value Write for Read Request */
#define	TMR_CVWRN_TCVWR_MSK			SHIFT0(0xffffffff)	/* TCVWR */
#define	TMR_CVWRN_TCVWR_BASE		0



/* -------------------- */


#endif	/* __INC_TMR_H */
